### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by dreambeaitbos** [lukrei/Triggerflow-Client#1]
Do you have automatic guns in this project?

**Comment by lukrei** [comment]
As long as you are on the enemies id with your crosshair it fires. If you are not on the enemies id it wont fire.
If you have a good recoil control then yes automatic guns work fine.

**Comment by dreambeaitbos** [comment]
> 只要你用十字准线在敌人的ID上，它就会开火。如果你不在敌人的ID上，它就不会开火。如果您有良好的后坐力控制，那么是的，自动枪工作正常。

  Do I just need to compile it and run it, and do I need anything else?

**Comment by lukrei** [comment]
You need memflow and all its dependencies like you would need if running radarflow2.
Also after compiling you need to create your own program which triggers the shoot event inside your vm.
Just an example write a small rust programm which acts as a Server and listens on udp port 1337 and then triggers shoot event somehow. There are multiple possibilities even via the shoot command ingame or sending keystrokes somehow over windows or game mechanics.

**Comment by dreambeaitbos** [comment]
> 您需要 memflow 及其所有依赖项，就像运行 radarflow2 时一样。此外，编译后，您需要创建自己的程序，以触发 vm 中的拍摄事件。举个例子，编写一个小型 rust 程序，它充当服务器并侦听 udp 端口 1337，然后以某种方式触发 shoot 事件。即使通过游戏中的射击命令或以某种方式通过窗口或游戏机制发送击键，也有多种可能性。
I was able to use radarflow2, but what you said about writing a rust program is a bit difficult for me because I'm not very good at it...

**Comment by lukrei** [comment]
> > 您需要 memflow 及其所有依赖项，就像运行 radarflow2 时一样。此外，编译后，您需要创建自己的程序，以触发 vm 中的拍摄事件。举个例子，编写一个小型 rust 程序，它充当服务器并侦听 udp 端口 1337，然后以某种方式触发 shoot 事件。即使通过游戏中的射击命令或以某种方式通过窗口或游戏机制发送击键，也有多种可能性。
> > I was able to use radarflow2, but what you said about writing a rust program is a bit difficult for me because I'm not very good at it...

The program could be in theory in any language:
Pseudocode:
create server listen on port 1337 udp
If udp_packet_received then
shoot
else
dont shoot

Where shoot can be an action via the shoot offset and injecting into the game or some other sort like talking to windows and send keystrokes to shoot.
With sv_cheats 1 enabled for example you could bind the shoot event on a key. If you now write a program which sends for example key "k" and bind shoot event to key "k" then your client would also work.
There are other possiblities like using ahk scripts or something.

**Comment by dreambeaitbos** [comment]
I need to use it to implement auto-fire on the platform, so I want to be able to do it without writing to memory, like radarflow2, so that I don't get detected and banned

> > > 您需要 memflow 及其所有依赖项，就像运行 radarflow2 时一样。此外，编译后，您需要创建自己的程序，以触发 vm 中的拍摄事件。举个例子，编写一个小型 rust 程序，它充当服务器并侦听 udp 端口 1337，然后以某种方式触发 shoot 事件。即使通过游戏中的射击命令或以某种方式通过窗口或游戏机制发送击键，也有多种可能性。
> > > I was able to use radarflow2, but what you said about writing a rust program is a bit difficult for me because I'm not very good at it...
> 
> The program could be in theory in any language: Pseudocode: create server listen on port 1337 udp If udp_packet_received then shoot else dont shoot
> 
> Where shoot can be an action via the shoot offset and injecting into the game or some other sort like talking to windows and send keystrokes to shoot.

I need to use it to implement auto-fire on the platform, so I want to be able to do it without writing to memory, like radarflow2, so that I don't get detected and banned

**Comment by lukrei** [comment]
You could use mouse macros for example. Some mices have programs to write makros or do it via AHK as I know AHK can also send mouse1 for example or try to find a different way to send mouse1 not to the game but to windows instead.

**Comment by dreambeaitbos** [comment]
> 例如，您可以使用鼠标宏。例如，一些鼠标具有编写 makros 或通过 AHK 执行的程序，例如，AHK 也可以发送 mouse1，或者尝试找到一种不同的方式将 mouse1 发送到 windows，而不是发送到游戏。

Thank you for your reply, do you have a code example for this, I think I might need to spend a lot of time looking into it

**Comment by lukrei** [comment]
of course you can try it via powershell:

Add-Type -Name User32 -Namespace Win32 -MemberDefinition @"
    [DllImport("user32.dll", CharSet=CharSet.Auto, CallingConvention=CallingConvention.StdCall)]
    public static extern void mouse_event(uint dwFlags, uint dx, uint dy, uint cButtons, uint dwExtraInfo);
"@

$port = 1337

$udpClient = New-Object System.Net.Sockets.UdpClient($port)

function SimulateMouseClick {
    $mouseLeftButtonDown = 0x0002
    $mouseLeftButtonUp = 0x0004
    [Win32.User32]::mouse_event($mouseLeftButtonDown, 0, 0, 0, 0)
    Start-Sleep -Milliseconds 100
    [Win32.User32]::mouse_event($mouseLeftButtonUp, 0, 0, 0, 0)
}

function HandleUdpPacket {
    param (
        [byte[]]$data
    )

    $receivedData = [System.Text.Encoding]::ASCII.GetString($data)
    Write-Host "Received UDP packet with data: $receivedData"

    SimulateMouseClick
}

try {
    Write-Host "UDP Server is listening on port $port..."

    while ($true) {
        $remoteEndPoint = New-Object System.Net.IPEndPoint ([System.Net.IPAddress]::Any, 0)
        $receivedData = $udpClient.Receive([ref]$remoteEndPoint)

        HandleUdpPacket -data $receivedData
    }
}
catch {
    Write-Host "Error occurred: $_.Exception.Message"
}
finally {
    $udpClient.Close()
}

**Comment by dreambeaitbos** [comment]
> of course you can try it via powershell:<br>
Add-Type -Name User32 -Namespace Win32 -MemberDefinition @" [DllImport("user32.dll", CharSet=CharSet.Auto, CallingConvention=CallingConvention.StdCall)] public static extern void mouse_event(uint dwFlags, uint dx, uint dy, uint cButtons, uint dwExtraInfo); "@
> 
> $port = 1337
> 
> $udpClient = New-Object System.Net.Sockets.UdpClient($port)
> 
> function SimulateMouseClick { $mouseLeftButtonDown = 0x0002 $mouseLeftButtonUp = 0x0004 [Win32.User32]::mouse_event($mouseLeftButtonDown, 0, 0, 0, 0) Start-Sleep -Milliseconds 100 [Win32.User32]::mouse_event($mouseLeftButtonUp, 0, 0, 0, 0) }
> 
> function HandleUdpPacket { param ( [byte[]]$data )
> 
> ```
> $receivedData = [System.Text.Encoding]::ASCII.GetString($data)
> Write-Host "Received UDP packet with data: $receivedData"
> 
> SimulateMouseClick
> ```
> 
> }
> 
> try { Write-Host "UDP Server is listening on port $port..."
> 
> ```
> while ($true) {
>     $remoteEndPoint = New-Object System.Net.IPEndPoint ([System.Net.IPAddress]::Any, 0)
>     $receivedData = $udpClient.Receive([ref]$remoteEndPoint)
> 
>     HandleUdpPacket -data $receivedData
> }
> ```
> 
> } catch { Write-Host "Error occurred: $_.Exception.Message" } finally { $udpClient.Close() }

I just found this code, which seems to be a mouse simulation, whether it is also possible to implement auto-fire without being banned：
if (active::trigger)
	{
		POINT p;
		const auto local_player = ent.local_pawn();
		const auto idx = mem.read<std::int32_t>(local_player + offsets::m_iIDEntIndex);

		if (GetAsyncKeyState(0x06))
		{
			if (idx != -1)
			{
				const auto controller = ent.crsh_idx_to_controller(idx);
				const auto hp = ent.player_hp(controller);

				if (ent.teamcheck(controller))
					return;

				if (hp > 100 || hp <= 0)
					return;

				GetCursorPos(&p);
				mouse_event(MOUSEEVENTF_LEFTDOWN, p.x, p.y, 0, 0);
				mouse_event(MOUSEEVENTF_LEFTUP, p.x, p.y, 0, 0);
			}
		}
	}

**Comment by lukrei** [comment]
you can try the code however i like to split the reading and writing part since I dont want that anyone who is using the repository gets vac banned by accident.
Create a new Fork and implement it there let me know if it was successfull.

I dont know if VAC differentiates between the offset shoot function which is built ingame or if you shoot manually.
Thats why the powershell script from above may not work on VAC secured servers because of emulated mouse events.
If you really want to play on VAC Servers with this use some kind of mouse software delivered by mouse vendor.

**Comment by dreambeaitbos** [comment]
> 您可以尝试代码，但是我喜欢拆分读取和写入部分，因为我不希望任何使用存储库的人意外地被禁止 vac。创建一个新的 Fork 并在那里实现它，让我知道它是否成功。
> 
> 我不知道 VAC 是否区分游戏中内置的偏置射击功能或手动射击。这就是为什么由于模拟的鼠标事件，上面的 powershell 脚本可能无法在 VAC 安全服务器上运行。如果您真的想在VAC服务器上玩这个游戏，请使用鼠标供应商提供的某种鼠标软件。

My gosh, this sounds complicated, I don't know if I'll be able to finish this project, I'm still thinking about how I can use trigger at the same time as radarflow2

**Comment by dreambeaitbos** [comment]
> > 您可以尝试代码，但是我喜欢拆分读取和写入部分，因为我不希望任何使用存储库的人意外地被禁止 vac。创建一个新的 Fork 并在那里实现它，让我知道它是否成功。
> > 我不知道 VAC 是否区分游戏中内置的偏置射击功能或手动射击。这就是为什么由于模拟的鼠标事件，上面的 powershell 脚本可能无法在 VAC 安全服务器上运行。如果您真的想在VAC服务器上玩这个游戏，请使用鼠标供应商提供的某种鼠标软件。
> 
> 我的天哪，这听起来很复杂，我不知道我是否能够完成这个项目，我还在考虑如何与 radarflow2 同时使用 trigger

I've heard that someone implements automatic fire by writing attack

**Comment by lukrei** [comment]
By the way the powershell code was generated by OpenAI. Maybe try to ask OpenAI how to accomplish this with mouse software.
I could imagine a mouse software has an API where you can start the script you define like click mouse1 button. This could be combined with a powershell program which listens on port 1337 like I wrote but instead of sending "SimulateMouseClick" event start mouse macro of mouse vendors software.

**Comment by dreambeaitbos** [comment]
> 顺便说一句，powershell 代码是由 OpenAI 生成的。也许试着问 OpenAI 如何使用鼠标软件做到这一点。我可以想象鼠标软件有一个 API，您可以在其中启动您定义的脚本，例如单击 mouse1 按钮。这可以与powershell程序结合使用，该程序像我写的那样在端口1337上侦听，但不是发送鼠标供应商软件的“SimulateMouseClick”事件启动鼠标宏。

How does your trigger auto-fire? Is it read-only or write-to-memory? Thank you for your answer, you're such a nice guy

**Comment by lukrei** [comment]
The Triggerflow-Client executed on Linux is read only via Memflow DMA.
It sends from Linux a UDP Packet to a Destination you can choose and from there you can execute for example the powershell script from above.
The UDP Packet is the sign to fire if no UDP Packet is received no enemy is in crosshair if udp packets are received it should fire.

So you could implement something like while udp packets received fire then stop like i did it in powershell script above.

**Comment by dreambeaitbos** [comment]
> 在 Linux 上执行的 Triggerflow-Client 通过 Memflow DMA 只读。它从 Linux 将 UDP 数据包发送到您可以选择的目标，然后您可以从那里执行例如上面的 powershell 脚本。 UDP 数据包是发射的标志，如果没有收到 UDP 数据包，则没有敌人处于十字准线中，如果收到 udp 数据包，它应该触发。
> 
> 因此，您可以实现类似 while udp 数据包收到 fire 然后停止的东西，就像我在上面的 powershell 脚本中所做的那样。

Then I think I can just use your trigger, I'm very interested in it! I don't have to look anywhere else to implement automatic fire, and if I want to use your project, I need to write it myself, right?

**Comment by dreambeaitbos** [comment]
> > 在 Linux 上执行的 Triggerflow-Client 通过 Memflow DMA 只读。它从 Linux 将 UDP 数据包发送到您可以选择的目标，然后您可以从那里执行例如上面的 powershell 脚本。UDP 数据包是发射的标志，如果没有收到 UDP 数据包，则没有敌人处于十字准线中，如果收到 udp 数据包，它应该触发。
> > 因此，您可以实现类似 while udp 数据包收到 fire 然后停止的东西，就像我在上面的 powershell 脚本中所做的那样。
> 
> 然后我想我可以使用你的扳机，我对它很感兴趣！我不需要寻找其他任何地方来实现自动射击，如果我想使用你的项目，我需要自己编写，对吧？

I still don't understand, if I use your project, can I directly compile and run the radar and auto-fire, or is it a separate auto-fire function?

**Comment by lukrei** [comment]
you could use Triggerflow-Client on Linux Server while you run my powershell script from above in the win vm yes.
But please add -insecure to cs2 startparameter and try it against bots. You may have to adjust the powershell code to stop fireing i did not try it to completion.

And you can also fork the code yes. Maybe inform the original developer of radarflow2 too so that he is aware of your project.

**Comment by dreambeaitbos** [comment]
> 您可以在 Linux Server 上使用 Triggerflow-Client，同时在 win vm yes 中从上面运行我的 powershell 脚本。但是请将 -insecure 添加到 cs2 start参数并尝试针对机器人。您可能需要调整 powershell 代码才能停止触发，我没有尝试完成。
> 
> 你也可以分叉代码，是的。也许也通知 radarflow2 的原始开发人员，以便他了解您的项目。

As it stands, if I run your project successfully, I can implement web radar and auto-fire, right?

**Comment by lukrei** [comment]
For Radar you would have to use superyu1337 web radar. Be aware i did not remove the listener to port 8000 so either you remove it from my Triggerflow-Client or you simply start radarflow2 first then Triggerflow-Client.

Triggerflow-Client may print an error message that socket 8000 is already in use but you can ignore this message trigger will still work.

I also adjusted the description and included the powershell script.

**Comment by dreambeaitbos** [comment]
> 对于雷达，你必须使用superyu1337 web雷达。请注意，我没有将侦听器删除到端口8000，所以要么您从我的Triggerflow-Client中删除它，要么您只需首先启动radarflow2，然后启动Triggerflow-Client。
> 
> Triggerflow-客户端可能会打印socket 8000已经在使用的错误消息，但是您可以忽略这个消息触发器仍然可以工作。
> 
> 我还调整了描述并包含了powershell脚本。

ok，thanks，i will try after i go home

**Comment by lukrei** [comment]
> > 对于雷达，你必须使用superyu1337 web雷达。请注意，我没有将侦听器删除到端口8000，所以要么您从我的Triggerflow-Client中删除它，要么您只需首先启动radarflow2，然后启动Triggerflow-Client。
> > Triggerflow-客户端可能会打印socket 8000已经在使用的错误消息，但是您可以忽略这个消息触发器仍然可以工作。
> > 我还调整了描述并包含了powershell脚本。
> 
> ok，thanks，i will try after i go home

I have created a new Triggerflow-Server.ps1 Powershell Script use it for testing purposes only. It should work for testing purposes so that it actually works like auto fire.

**Comment by dreambeaitbos** [comment]
> > > 对于雷达，你必须使用superyu1337 web雷达。请注意，我没有将侦听器删除到端口8000，所以要么您从我的Triggerflow-Client中删除它，要么您只需首先启动radarflow2，然后启动Triggerflow-Client。
> > > Triggerflow-客户端可能会打印socket 8000已经在使用的错误消息，但是您可以忽略这个消息触发器仍然可以工作。
> > > 我还调整了描述并包含了powershell脚本。
> > 
> > 
> > ok，thanks，i will try after i go home
> 
> I have created a new Triggerflow-Server.ps1 Powershell Script use it for testing purposes only. It should work for testing purposes so that it actually works like auto fire.

I have no time to test today, so I can only test tomorrow. Is your new change for testing? How to operate it?

**Comment by lukrei** [comment]
> > > > 对于雷达，你必须使用superyu1337 web雷达。请注意，我没有将侦听器删除到端口8000，所以要么您从我的Triggerflow-Client中删除它，要么您只需首先启动radarflow2，然后启动Triggerflow-Client。
> > > > Triggerflow-客户端可能会打印socket 8000已经在使用的错误消息，但是您可以忽略这个消息触发器仍然可以工作。
> > > > 我还调整了描述并包含了powershell脚本。
> > > 
> > > 
> > > ok，thanks，i will try after i go home
> > 
> > 
> > I have created a new Triggerflow-Server.ps1 Powershell Script use it for testing purposes only. It should work for testing purposes so that it actually works like auto fire.
> 
> I have no time to test today, so I can only test tomorrow. Is your new change for testing? How to operate it?

Just go to the readme of the project and do everything until the powershell script is mentioned.
You can open "Windows Powershell ISE" as Administrator and paste in the code of the ps1 File in my Git Repository.

**Comment by dreambeaitbos** [comment]
> > > > > 对于雷达，你必须使用superyu1337 web雷达。请注意，我没有将侦听器删除到端口8000，所以要么您从我的Triggerflow-Client中删除它，要么您只需首先启动radarflow2，然后启动Triggerflow-Client。
> > > > > Triggerflow-客户端可能会打印socket 8000已经在使用的错误消息，但是您可以忽略这个消息触发器仍然可以工作。
> > > > > 我还调整了描述并包含了powershell脚本。
> > > > 
> > > > 
> > > > ok，thanks，i will try after i go home
> > > 
> > > 
> > > I have created a new Triggerflow-Server.ps1 Powershell Script use it for testing purposes only. It should work for testing purposes so that it actually works like auto fire.
> > 
> > 
> > I have no time to test today, so I can only test tomorrow. Is your new change for testing? How to operate it?
> 
> Just go to the readme of the project and do everything until the powershell script is mentioned. You can open "Windows Powershell ISE" as Administrator and paste in the code of the ps1 File in my Git Repository.

Why do I get the following error, I have already installed all the required environments:
Launched webserver at http://172.26.40.19:8000
2024-04-07T04:58:04.542Z ERROR [memflow::plugins] unable to find plugin with name 'qemu'.
2024-04-07T04:58:04.542Z ERROR [memflow::plugins] possible available `Connector` plugins are: 
2024-04-07T04:58:04.542Z ERROR [memflow::plugins] outdated/mismatched `Connector` plugins where found at: 
2024-04-07T04:58:04.542Z ERROR [radarflow] Error in dma thread: [inventory: plugin not found]

**Comment by lukrei** [comment]
Did you run ./run.sh?

**Comment by dreambeaitbos** [comment]
> Did you run ./run.sh?

yes,but i meet this erro

**Comment by lukrei** [comment]
did you install the dkms memflow module and all its connectors via memflowup?
https://github.com/memflow/memflow-kvm/tree/main

**Comment by dreambeaitbos** [comment]
> 您是否通过 memflowup 安装了 DKMS Memflow 模块及其所有连接器？

I can run radarflow2 without any errors. In theory, I should have installed the required environment. Is there any other environment required for your project?

**Comment by lukrei** [comment]
the cargo.toml and cargo.lock contains the dependencies. i compared them with radarflow2 and they are identical.
maybe try to run radarflow2 again and see if you can still run it.

also try to git clone the repository again.

**Comment by dreambeaitbos** [comment]
> cargo.toml 和 cargo.lock 包含依赖项。我将它们与 Radarflow2 进行了比较，它们是相同的。也许尝试再次运行 Radarflow2，看看是否仍然可以运行它。
> 
> 还要尝试再次 git 克隆存储库。

But I can use radarflow2 normally, so there shouldn't be any environmental issues, I'm confused

**Comment by lukrei** [comment]
try to redownload Triggerflow and make sure you are NOT root user. then try the steps from readme again.

**Comment by dreambeaitbos** [comment]
> try to redownload Triggerflow and make sure you are NOT root user. then try the steps from readme again.
I ran into this issue again when compiling:
error: failed to run custom build command for `radarflow v0.2.3 (/home/pdx/Triggerflow-Client)`

Caused by:
  process didn't exit successfully: `/home/pdx/Triggerflow-Client/target/release/build/radarflow-68dcc93e0b8e6da5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:26:29:
  Downloading info.json
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lukrei** [comment]
try sudo rm -r /home/pdx/Triggerflow-Client/target/ and try again please

**Comment by dreambeaitbos** [comment]
> try sudo rm -r /home/pdx/Triggerflow-Client/target/ and try again please

error: failed to run custom build command for `radarflow v0.2.3 (/home/pdx/Triggerflow-Client)`

Caused by:
  process didn't exit successfully: `/home/pdx/Triggerflow-Client/target/release/build/radarflow-68dcc93e0b8e6da5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:26:29:
  Downloading info.json
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lukrei** [comment]
do you have some sort of firewall?
try to run with RUST_BACKTRACE=1 and make sure you can access:
https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/info.json

**Comment by dreambeaitbos** [comment]
> do you have some sort of firewall? try to run with RUST_BACKTRACE=1 and make sure you can access: https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/info.json
I click on this URL to show this:
{
  "build_number": 14001,
  "timestamp": "2024-04-07T08:19:03.265339800+00:00"
}

**Comment by dreambeaitbos** [comment]
> 你有某种防火墙吗？尝试以 RUST_BACKTRACE=1 运行，并确保您可以访问： https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/info.json

I can manually download it and replace it in the file, right?

**Comment by lukrei** [comment]
can you visit the site in your browser and then check certificate chain? i have the feeling that something is doing a TLS inspection.
![grafik](https://github.com/lukrei/Triggerflow-Client/assets/113136700/063cfdc1-6ca9-4b31-8466-18c1445878e4)

**Comment by dreambeaitbos** [comment]
> 您可以在浏览器中访问该站点，然后检查证书链吗？我有一种感觉，有些东西正在做TLS检查。 ![grafik](https://private-user-images.githubusercontent.com/113136700/320270507-063cfdc1-6ca9-4b31-8466-18c1445878e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODE5MzcsIm5iZiI6MTcxMjQ4MTYzNywicGF0aCI6Ii8xMTMxMzY3MDAvMzIwMjcwNTA3LTA2M2NmZGMxLTZjYTktNGIzMS04NDY2LTE4YzE0NDU4NzhlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTIwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzMxMTA4ZDk4YmRjOWRkNDk3ZDhjNjNiZDJkMDlhNjIxNTA3NzVjZTNkNGY2NzY0MjQ2ODdiNzE0ZGUwZDkyJlgtQW16LVNpZ25lZEh
lYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iaprgvnBp9Z_4NYGKwYfHdYVHynVFGHOL2BFYdj8Qgs


I went through the rebuild and got the following error:
    Running `target/release/radarflow`
Launched webserver at http://172.26.40.19:8000
2024-04-07T09:19:50.447Z ERROR [memflow::error] connector: not found (Unable to find the QEMU guest memory map. This usually indicates insufficient permissions to acquire the QEMU memory maps. Are you running with appropiate access rights?)
2024-04-07T09:19:50.447Z ERROR [memflow::plugins::util] connector: not found
2024-04-07T09:19:50.447Z ERROR [radarflow] Error in dma thread: [connector: not found]

**Comment by lukrei** [comment]
okay so you only run rebuild.sh? i also had this message please continue with run.sh

**Comment by dreambeaitbos** [comment]
> 好吧，所以你只跑 rebuild.sh？我也有这个消息，请继续 run.sh

pdx@pdx-desktop:~/Triggerflow-Client$ ./run.sh
[sudo] pdx 的密码： 
Launched webserver at http://172.26.40.19:8000
2024-04-07T09:22:56.815Z ERROR [memflow::plugins] unable to find plugin with name 'qemu'.
2024-04-07T09:22:56.815Z ERROR [memflow::plugins] possible available `Connector` plugins are: 
2024-04-07T09:22:56.815Z ERROR [memflow::plugins] outdated/mismatched `Connector` plugins where found at: 
2024-04-07T09:22:56.815Z ERROR [radarflow] Error in dma thread: [inventory: plugin not found]

**Comment by lukrei** [comment]
okay thats strange it seems something is messed up with your memflow plugins. pleases try to update them. i dont know why radarflow2 is working but this message comes directly from memflow not from triggerflow.
please look at:
https://www.youtube.com/watch?v=1RQ0ewwtvGo&list=PLrC4R7zDrxB3RSJQk9ahmXNCw8m3pdP6z&index=3&pp=iAQB

**Comment by lukrei** [comment]
Also try to compare Cargo.toml and Cargo.lock between my github repository and your local files.
You may need to update dependencies:
https://manpages.ubuntu.com/manpages/focal/en/man1/cargo-update.1.html

You may look in this discsord channel under support help.
https://discord.gg/2jMEewXW

someone had a similar problem:
` 2024-04-03T11:14:53.992Z INFO  memflow::plugins > scanning "/usr/local/lib/memflow" for libraries
 2024-04-03T11:14:54.007Z WARN  memflow::plugins > MEMFLOW_CONNECTOR_KVM has a different version. version -9 required, found 1.
....
 2024-04-03T11:25:33.076Z ERROR memflow::plugins > unable to find plugin with name 'kvm'.
 2024-04-03T11:25:33.076Z ERROR memflow::plugins > possible available `Connector` plugins are:
 2024-04-03T11:25:33.076Z ERROR memflow::plugins > outdated/mismatched `Connector` plugins where found at: /usr/local/lib/memflow/libmemflow_kvm.dev.so, /home/k/.local/lib/memflow/libmemflow_kvm.dev.so`

he edited the Cargo Files:
You may have to replace the memflow version according to your version:
[workspace.dependencies.memflow]
version = "=0.2.0-beta10"
default-features = false
features = ["plugins", "os_helpers", "64_bit_mem", "dummy_mem"]

[workspace.dependencies.memflow-win32]
version = "=0.2.0-beta10"

**Comment by SuperLifeown** [comment]
![9baa5a92269ce42e834ef770c9615318](https://github.com/lukrei/Triggerflow-Client/assets/163156194/c25c0027-ee88-45ea-bd7f-965f26958b38)
![855638960c0956278b227488b9b021e4](https://github.com/lukrei/Triggerflow-Client/assets/163156194/b0eb7b72-cbec-4e85-b9a4-98d31baedc0b)
The radar started, but I'm not sure about the trigger.
What's going on? sad
